/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoazul;

import com.sun.glass.events.KeyEvent;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.StringReader;
import java.lang.Character.UnicodeBlock;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.TargetDataLine;
import javax.speech.AudioException;
import javax.speech.Central;
import javax.speech.EngineException;
import javax.speech.EngineStateError;
import javax.speech.synthesis.Synthesizer;
import javax.speech.synthesis.SynthesizerModeDesc;
import javax.speech.synthesis.Voice;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
/**
 *
 * @author Gabriel Olivares Armijo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Binary Speaker V 3.0- Blue Proyect/Proyecto Azul/青プロジェクト");
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/LogoMarca.jpg")).getImage());
    
        
        ((JPanel)getContentPane()).setOpaque(false); ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/Fondo proyecto 2.jpg")); 
        JLabel fondo= new JLabel(); fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); fondo.setBounds(0,0,uno.getIconHeight(),uno.getIconWidth());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtadecir = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDiccionario = new javax.swing.JButton();
        btnSinonimos = new javax.swing.JButton();
        btnDictionay = new javax.swing.JButton();
        btnSynonym = new javax.swing.JButton();
        btnTtspanish = new javax.swing.JButton();
        btnespaing = new javax.swing.JButton();
        btnespjap = new javax.swing.JButton();
        btnTtJapanese = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(21474, 21474));

        txtadecir.setColumns(20);
        txtadecir.setFont(new java.awt.Font("Monospaced", 0, 20)); // NOI18N
        txtadecir.setRows(5);
        txtadecir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadecirKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtadecir);

        jButton3.setText("Hablar/Speak/話す");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("日本語で上手く話すため、「ひあらがな」や「カタカナ」など書いて、ボタンを押して下さい。");

        jLabel2.setText("Para reproducir lo que quiere decir, escriba en el cuadro y pulse el botón.");

        jLabel3.setText("In order to play your speech, write it in the blank and push the button.");

        jLabel4.setBackground(new java.awt.Color(255, 204, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(33, 88, 255));
        jLabel4.setText("Binary Speaker");
        //jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Blue Proyect/Proyecto Azul/青プロジェクト");

        btnDiccionario.setText("Diccionario");
        btnDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiccionarioActionPerformed(evt);
            }
        });

        btnSinonimos.setText("Sinónimo");
        btnSinonimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinonimosActionPerformed(evt);
            }
        });

        btnDictionay.setText("Dictionary");
        btnDictionay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDictionayActionPerformed(evt);
            }
        });

        btnSynonym.setText("Synonym");
        btnSynonym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSynonymActionPerformed(evt);
            }
        });

        btnTtspanish.setText("Translate to Spanish");
        btnTtspanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTtspanishActionPerformed(evt);
            }
        });

        btnespaing.setText("Traducir al Inglés");
        btnespaing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespaingActionPerformed(evt);
            }
        });

        btnespjap.setText("Traducir al Japonés");
        btnespjap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespjapActionPerformed(evt);
            }
        });

        btnTtJapanese.setText("Translate to japanese");
        btnTtJapanese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTtJapaneseActionPerformed(evt);
            }
        });

        jButton1.setText("Speak from Word document/Hablar desde documento Word");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save written text in Word file/Guardar texto escrito en Word");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

      

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(415, 415, 415))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(196, 196, 196)
                        .addComponent(JBotonHablar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDictionay)
                            .addComponent(btnSynonym)
                            .addComponent(btnTtspanish)
                            .addComponent(btnTtJapanese))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnespjap)
                            .addComponent(btnespaing)
                            .addComponent(btnSinonimos)
                            .addComponent(btnDiccionario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDiccionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSinonimos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnespaing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnespjap)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDictionay)
                        .addGap(18, 18, 18)
                        .addComponent(btnSynonym)
                        .addGap(18, 18, 18)
                        .addComponent(btnTtspanish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTtJapanese)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JBotonHablar))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Runnable r =new Metodoboton(this.txtadecir);
    Thread hilo= new Thread(r);
     hilo.start();
            if(!this.txtadecir.getText().isEmpty())
 {
       JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
         this.txtadecir.setText("");
 }
 else {  
       JOptionPane.showMessageDialog(null, "No hay nada escrito/There's nothing written/何も書いてありません。"); 
       this.txtadecir.setText("");
 }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtadecirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadecirKeyTyped
     char ke=evt.getKeyChar();
     
     if(ke==KeyEvent.VK_ENTER)
     {
         
         
         
         Runnable r =new Metodoboton(this.txtadecir);
    Thread hilo= new Thread(r);
     hilo.start();
            if(!this.txtadecir.getText().equalsIgnoreCase("\n"))
 {
       JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
         this.txtadecir.setText("");
 }
 else {  
       JOptionPane.showMessageDialog(null, "No hay nada escrito/There's nothing written/何も書いてありません。"); 
       this.txtadecir.setText("");
 }
     }
    }//GEN-LAST:event_txtadecirKeyTyped

    private void btnSynonymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSynonymActionPerformed
      String url = "http://www.wordreference.com/synonyms/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
            this.txtadecir.setText(null);
            JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSynonymActionPerformed

    private void btnDictionayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDictionayActionPerformed
       String url = "http://www.wordreference.com/definition/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDictionayActionPerformed

    private void btnTtspanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTtspanishActionPerformed
     String url = "http://www.wordreference.com/es/translation.asp?tranword="+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
             
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTtspanishActionPerformed

    private void btnTtJapaneseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTtJapaneseActionPerformed
        String url = "http://www.wordreference.com/enja/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTtJapaneseActionPerformed

    private void btnespaingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespaingActionPerformed
String url = "http://www.wordreference.com/es/en/translation.asp?spen="+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnespaingActionPerformed

    private void btnSinonimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinonimosActionPerformed
       String url = "http://www.wordreference.com/sinonimos/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSinonimosActionPerformed

    private void btnDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiccionarioActionPerformed
         String url = "http://www.wordreference.com/definicion/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDiccionarioActionPerformed

    private void btnespjapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespjapActionPerformed
 String url = "http://diccionario.reverso.net/espanol-japones/"+this.txtadecir.getText();
        try {
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);
             this.txtadecir.setText(null);
             JOptionPane.showMessageDialog(null, "Proceso exitoso/Successful Process/プロセス成功"); 
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnespjapActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           
             Runnable r =new Codigo_boton_word(this.jButton1);
    Thread hilo= new Thread(r);
     hilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Runnable r =new Botoncrearword(this.jButton2,this.txtadecir);
        
    Thread hilo= new Thread(r);
     hilo.start();
          } catch (java.lang.NullPointerException ex) {
                    JOptionPane.showMessageDialog(null, "File wasn't selected/No se eligió archivo/ファイルを選べませんでした。");
                    
          }
        
                  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBotonHablarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotonHablarActionPerformed
        
    Runnable r =new Metodohablar(this.txtadecir);
    Thread hilo= new Thread(r);
     hilo.start();       
    }//GEN-LAST:event_JBotonHablarActionPerformed
private boolean isHiragana(final char c)
{
     return (Character.UnicodeBlock.of(c)==Character.UnicodeBlock.HIRAGANA);
}

private boolean isKatakana(final char c)
{
     return (Character.UnicodeBlock.of(c)==Character.UnicodeBlock.KATAKANA);
}
private boolean isCharCJK(final char c) {
    if ((Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_COMPATIBILITY_FORMS)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_RADICALS_SUPPLEMENT)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.CJK_SYMBOLS_AND_PUNCTUATION)
            || (Character.UnicodeBlock.of(c) == Character.UnicodeBlock.ENCLOSED_CJK_LETTERS_AND_MONTHS)) {
        return true;
    }
    return false;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotonHablar;
    private javax.swing.JButton btnDiccionario;
    private javax.swing.JButton btnDictionay;
    private javax.swing.JButton btnSinonimos;
    private javax.swing.JButton btnSynonym;
    private javax.swing.JButton btnTtJapanese;
    private javax.swing.JButton btnTtspanish;
    private javax.swing.JButton btnespaing;
    private javax.swing.JButton btnespjap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtadecir;
    // End of variables declaration//GEN-END:variables
}
